### PR TITLE
Update minimum Puppet version to 3.x

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by ekohl** [comment]
Is this already the case or just reflecting the policy in the metadata?

**Comment by roidelapluie** [comment]
No one knows if it is already the case because it is not tested anymore.

As it is not tested we should state that in metadata.json.

**Comment by ekohl** [comment]
In that case I agree and think we should do this in all our modules

**Comment by mmoll** [comment]
Merged, merci @roidelapluie!
This should be done to all our modules, but we still have a bit time until the next release cycle. :cyclone:

**Pull request merged**
