### PR TITLE
Ensure the directory is present before using git.

### LINKED ISSUE #17: Chown to $user:$group for git_repo, mkdir with root
Hello:

I received this error on my run of puppet:

````shell
Notice: /Stage[main]/Puppet::Server::Config/Git::Repo[puppet_repo]/Exec[git_repo_for_puppet_repo]/returns: fatal: cannot mkdir /opt/puppet.git: Permission denied
Error: /usr/bin/git init --bare /opt/puppet.git returned 128 instead of one of [0]
Error: /Stage[main]/Puppet::Server::Config/Git::Repo[puppet_repo]/Exec[git_repo_for_puppet_repo]/returns: change from notrun to 0 failed: /usr/bin/git init --bare /opt/puppet.git returned 128 instead of one of [0]
Notice: /Stage[main]/Puppet::Server::Config/File[/opt/puppet.git/hooks/post-receive]: Dependency Exec[git_repo_for_puppet_repo] has failures: true
Warning: /Stage[main]/Puppet::Server::Config/File[/opt/puppet.git/hooks/post-receive]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Server::Service/Service[puppetserver]: Dependency Exec[git_repo_for_puppet_repo] has failures: true
Warning: /Stage[main]/Puppet::Server::Service/Service[puppetserver]: Skipping because of failed dependencies
````

At this line, it looks like it tries to make the owner of the git repo the puppet user, and it does that by making the directory as that user.

https://github.com/theforeman/puppet-puppet/blob/0d64709f48eb74f4e79982aa6a8a2b7eb7279b31/manifests/server/config.pp#L114

The corresponding git code is here: 

https://github.com/theforeman/puppet-git/blob/master/manifests/repo.pp#L46

Could it mkdir as the root user and then chown to the specified user instead?

As an aside, could we also add a $group parameter for the same reasons?

### PR DESCRIPTION
**Pull request by jyaworski**
Closes GH-17.

### CODE REVIEW

**Comment by mmoll** [comment]
:+1:
plase add "closes GH-17" to the commit message.

**Comment by jyaworski** [comment]
@mmoll edited. Thanks.

**Comment by brandonweeks** [comment]
:+1:

**Comment by mmoll** [comment]
merged, dzięki @jyaworski!

**Pull request merged**
