### PR TITLE
Allow arbitrary arguments string. Fixes #19.

### LINKED ISSUE #19: Ability to override arguments in git init/clone
Hello:

Looking at https://github.com/theforeman/puppet-git/blob/master/manifests/repo.pp I don't see a way to set, for example, core.sharedrepository. Can we have the ability to set params on init/clone as part of the defined type?

### PR DESCRIPTION
**Pull request by jyaworski**
Closes GH-19.

### CODE REVIEW

**Comment by brandonweeks** [comment]
I think this is a little confusing now since it overwrites the "--bare" flags instead of appending.

**Comment by jyaworski** [comment]
@brandonweeks good point. I refactored it.

**Comment by mmoll** [comment]
I'd like to see a spec test for this, :+1: otherwise.

**Comment by jyaworski** [comment]
@mmoll I didn't see a spec test for the entire define, so I didn't write one. I'll add one, though.

**Comment by jyaworski** [comment]
@mmoll good to go.

**Comment by mmoll** [comment]
@jyaworski Thanks, this is looking very good. It would be nice to have also a test without args, but that won't hold back the merging, IMHO, so :+1: from me.

**Comment by brandonweeks** [comment]
Awesome! :+1:

**Comment by mmoll** [comment]
please rebase

**Comment by jyaworski** [comment]
@mmoll done. Sorry for the delay. Wesołych Świąt. :)

**Comment by mmoll** [comment]
Merged, dzięki i również Wesołych Świąt Tobie! :christmas_tree:

**Pull request merged**
